### ISSUE TITLE
Test issue showing Firehiwot

### ISSUE THREAD

**Issue by ivogeorg** [coloradocube/balloonsat-shell#1]
# Description

A short description of the issue with the main points clearly stated.

# Knowledge

Links to resources, relevant to the issue/task and its solution/implementation.

# Deliverables

The result of this issue/task being completed.

**Comment by firew2021** [comment]
Hi @DannyS10

**Comment by DannyS10** [comment]
Hey I got the extra thick foam board @firew2021
